#!/bin/sh
# Exercise: Identifiy the default gateway in the routing table

netstat -rn | head -n 10 | grep Gateway | 
awk '{printf "\x1B[1m%-17s %-17s %-17s %-17s %-10s %-10s %-10s\x1B[0m\n", $1, $2, $3, $4, $5, $6, $7}' && 
netstat -rn | head -n 10 | grep default | 
awk '{printf "\x1B[32m\x1B[1m%-17s \x1B[34m%-17s\x1B[0m \x1B[1m%-17s %-17s %3s %12s %s\n", $1, $2, $3, $4, $5, $6, $7}'
