#!/bin/bash
# Exercise: Figure out the exact size of each folder of /var in a humanly understandable way
#           followed by the path of it.

sudo du -sh /var/*

# "-s" - summary;
# "du" - disk usage
