#!/bin/bash
# Exercise: Write a script which displays only the login, UID and Path of each entry of the
#           /etc/passwd file.

printf "%-22s %-10s %-20s\n" "Login" "UID" "Path"
awk -F: '{printf "%-22s %-10s %-20s\n", $1, $3, $6}' /etc/passwd
